---
kubernetes:
  credentials:
    kind: gcloud
    project: internal-sentry
    cluster: primary
    zone: us-central1-b

steps:
  - kind: KubernetesDeployment
    selector:
      label_selector: service=release-registry
      namespace: default
    containers:
      - image: us.gcr.io/sentryio/sentry-release-registry:{sha}
        name: release-registry
